version: '3.7'

volumes:
  prometheus_data: { }
  grafana_data: { }

networks:
  front-tier:
  back-tier:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./models:/app/models
    ports:
      - "8082:8080"
    networks:
      - back-tier
      - front-tier

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - back-tier
    restart: always